skip-changelog:
- .github/**/*
- .gitignore
- Jenkinsfile
- .mvn/**/*
- .sonarcloud.properties

dependencies:
- pom.xml

documentation:
- CHANGELOG.adoc
- CONTRIBUTING.adoc
- images/*.png
- MIT-LICENSE
- Priorities.adoc
- README.adoc

test:
- src/test/**/*
